# -*- coding: utf-8 -*-
"""heart data xgboost

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IlmokQMgtblpj2bcVD-UilTpmP7Oc87q
"""

import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

df=pd.read_csv("/content/heart.csv")

df.head()

df.info()

df.isnull().sum()

df.info()

df.duplicated().sum()

df.tail()

df.hist(figsize=(10,10))

df.boxplot()

df.isnull().sum()

sns.pairplot(df)

df.columns

X=df.drop('target',axis=1)

X

y=df['target']

y

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

y.shape,y_train.shape,y_test.shape

pip install xgboost

import xgboost as xgb

xgb_model=xgb.XGBClassifier()

xgb_model

xgb_model.fit(X_train,y_train)

xgb_model.score(X_train,y_train)

# Auto ML

from sklearn.ensemble import RandomForestClassifier

from sklearn.ensemble import AdaBoostClassifier

from sklearn.ensemble import GradientBoostingClassifier

from xgboost import XGBClassifier

rfc = RandomForestClassifier()

adaboost = AdaBoostClassifier()

gboost = GradientBoostingClassifier()

XGBModel = XGBClassifier()

models=[rfc,adaboost,gboost,XGBModel]

import time

for m in models:
    print(m)
    time.sleep(1)



xgb_model.score(X_test, y_test)

import warnings

warnings.filterwarnings('ignore')

X_train.shape,X_test.shape,X.shape

y_train.shape,y_test.shape,y.shape

for m in models :
    print(m)
    time.sleep(2)

for m in models :
    m.fit(X_train, y_train)
    scr = m.score(X_test, y_test)
    print(m,end = " == ")
    print(scr)
    time.sleep(2)

